from enum import Enum

class TipoGasto(Enum):
    TRANSPORTE = "TRANSPORTE"
    ALOJAMIENTO = "ALOJAMIENTO"
    ALIMENTACION = "ALIMENTACION"
    ENTRETENIMIENTO = "ENTRETENIMIENTO"
    COMPRAS = "COMPRAS"